name: Build and Push KVNRV to Docker Hub
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: sh ./build.sh
        env:
          PUBLIC_URL: /
          REACT_APP_WHITELABEL: KVNRV
      - name: Check Tag
        id: check_tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+\-KVNRV$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Release Version
        if: steps.check_tag.outputs.match == 'true'
        run: |
          docker tag mqtt victronenergy/venus-docker:${GITHUB_REF##*/}
          echo '${{ secrets.DOCKERHUB_TOKEN }}' | docker login --username aleximb --password-stdin
          docker push victronenergy/venus-docker:${GITHUB_REF##*/}
